// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: doorman.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenge string `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
}

func (x *AccessCheckRequest) Reset() {
	*x = AccessCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckRequest) ProtoMessage() {}

func (x *AccessCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckRequest.ProtoReflect.Descriptor instead.
func (*AccessCheckRequest) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{0}
}

func (x *AccessCheckRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type OpenDoorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenge string `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
}

func (x *OpenDoorRequest) Reset() {
	*x = OpenDoorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDoorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDoorRequest) ProtoMessage() {}

func (x *OpenDoorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDoorRequest.ProtoReflect.Descriptor instead.
func (*OpenDoorRequest) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{1}
}

func (x *OpenDoorRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type AccessCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasAccess    bool `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	IsFuks       bool `protobuf:"varint,2,opt,name=is_fuks,json=isFuks,proto3" json:"is_fuks,omitempty"`
	IsActiveFuks bool `protobuf:"varint,3,opt,name=is_active_fuks,json=isActiveFuks,proto3" json:"is_active_fuks,omitempty"`
}

func (x *AccessCheckResponse) Reset() {
	*x = AccessCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckResponse) ProtoMessage() {}

func (x *AccessCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckResponse.ProtoReflect.Descriptor instead.
func (*AccessCheckResponse) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{2}
}

func (x *AccessCheckResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *AccessCheckResponse) GetIsFuks() bool {
	if x != nil {
		return x.IsFuks
	}
	return false
}

func (x *AccessCheckResponse) GetIsActiveFuks() bool {
	if x != nil {
		return x.IsActiveFuks
	}
	return false
}

type OpenDoorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Open         bool                 `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	OpenDuration *durationpb.Duration `protobuf:"bytes,2,opt,name=open_duration,json=openDuration,proto3" json:"open_duration,omitempty"`
}

func (x *OpenDoorResponse) Reset() {
	*x = OpenDoorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDoorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDoorResponse) ProtoMessage() {}

func (x *OpenDoorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDoorResponse.ProtoReflect.Descriptor instead.
func (*OpenDoorResponse) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{3}
}

func (x *OpenDoorResponse) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *OpenDoorResponse) GetOpenDuration() *durationpb.Duration {
	if x != nil {
		return x.OpenDuration
	}
	return nil
}

var File_doorman_proto protoreflect.FileDescriptor

var file_doorman_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d,
	0x61, 0x6e, 0x2e, 0x76, 0x32, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22, 0x2f, 0x0a, 0x0f, 0x4f, 0x70, 0x65,
	0x6e, 0x44, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22, 0x73, 0x0a, 0x13, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61, 0x73, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x66, 0x75, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x73, 0x46, 0x75, 0x6b, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x73, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x75, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x46, 0x75, 0x6b, 0x73, 0x22,
	0x66, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x3e, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x6e, 0x5f,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xc8, 0x01, 0x0a, 0x07, 0x44, 0x6f, 0x6f, 0x72,
	0x6d, 0x61, 0x6e, 0x12, 0x62, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x28, 0x2e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x64,
	0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e,
	0x2e, 0x76, 0x32, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x44,
	0x6f, 0x6f, 0x72, 0x12, 0x25, 0x2e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x2e,
	0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x32, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44,
	0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x76,
	0x32, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_doorman_proto_rawDescOnce sync.Once
	file_doorman_proto_rawDescData = file_doorman_proto_rawDesc
)

func file_doorman_proto_rawDescGZIP() []byte {
	file_doorman_proto_rawDescOnce.Do(func() {
		file_doorman_proto_rawDescData = protoimpl.X.CompressGZIP(file_doorman_proto_rawDescData)
	})
	return file_doorman_proto_rawDescData
}

var file_doorman_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_doorman_proto_goTypes = []interface{}{
	(*AccessCheckRequest)(nil),  // 0: endpoints.doorman.v2.AccessCheckRequest
	(*OpenDoorRequest)(nil),     // 1: endpoints.doorman.v2.OpenDoorRequest
	(*AccessCheckResponse)(nil), // 2: endpoints.doorman.v2.AccessCheckResponse
	(*OpenDoorResponse)(nil),    // 3: endpoints.doorman.v2.OpenDoorResponse
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_doorman_proto_depIdxs = []int32{
	4, // 0: endpoints.doorman.v2.OpenDoorResponse.open_duration:type_name -> google.protobuf.Duration
	0, // 1: endpoints.doorman.v2.Doorman.CheckAccess:input_type -> endpoints.doorman.v2.AccessCheckRequest
	1, // 2: endpoints.doorman.v2.Doorman.OpenDoor:input_type -> endpoints.doorman.v2.OpenDoorRequest
	2, // 3: endpoints.doorman.v2.Doorman.CheckAccess:output_type -> endpoints.doorman.v2.AccessCheckResponse
	3, // 4: endpoints.doorman.v2.Doorman.OpenDoor:output_type -> endpoints.doorman.v2.OpenDoorResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_doorman_proto_init() }
func file_doorman_proto_init() {
	if File_doorman_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_doorman_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDoorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDoorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doorman_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doorman_proto_goTypes,
		DependencyIndexes: file_doorman_proto_depIdxs,
		MessageInfos:      file_doorman_proto_msgTypes,
	}.Build()
	File_doorman_proto = out.File
	file_doorman_proto_rawDesc = nil
	file_doorman_proto_goTypes = nil
	file_doorman_proto_depIdxs = nil
}
